# Spring properties
spring:
  application:
    name: people-services  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  #thymeleaf:
    #cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    #prefix: classpath:/templates/    # Trailing / mandatory


  cloud:
    config:
      uri: http://localhost:8080
                                    # Template location for this application only


# HTTP Server
server:
 port: ${PORT:${SERVER_PORT:0}}